# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_TFZaN4ObFteXlWFnS9m-MmWIeChiEU-
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 10, 100)
y = np.sin(x)

plt.plot(x, y)
plt.title('Sinus Funktsiyasi Grafiki')
plt.xlabel('X qiymatlari')
plt.ylabel('Sin(X)')
plt.show()

x = np.random.rand(50)
y = np.random.rand(50)

plt.scatter(x, y, color='blue')
plt.title('Tasodifiy Nuqtalar Scatter Grafiki')
plt.xlabel('X qiymatlari')
plt.ylabel('Y qiymatlari')
plt.show()

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("bmw m3.jpg")
cv2_imshow(rasm)

oqqora= cv2.cvtColor(rasm, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm1=cv2.imread("bmw m5.webp")
cv2_imshow(rasm1)

oqqora= cv2.cvtColor(rasm1, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm2=cv2.imread("olma.webp")
cv2_imshow(rasm2)

oqqora= cv2.cvtColor(rasm2, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

import pandas as pd
# Yuklangan fayl nomini o'zgartiring
df = pd.read_csv('WHO COVID-19 cases(3).csv')
print(df)